version: 2.1

orbs:
  common-config: aditi7gupta7/common-config-javaa@1.0.0

workflows:
  version: 2
  build:
    jobs:
      - common-config/common_build
      - java_build:
          executor: common-config/default
